# This rule is not used by the project braid itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the braid.james-parker.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: braid
    app.kubernetes.io/managed-by: kustomize
  name: objectversion-editor-role
rules:
- apiGroups:
  - braid.james-parker.dev
  resources:
  - objectversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - braid.james-parker.dev
  resources:
  - objectversions/status
  verbs:
  - get
